// emojiData.js
const emojiData = [
  { symbol: "😀" },
  { symbol: "😃" },
  { symbol: "😄" },
  { symbol: "😁" },
  { symbol: "😆" },
  { symbol: "😅" },
  { symbol: "😂" },
  { symbol: "🤣" },
  { symbol: "😊" },
  { symbol: "😇" },
  { symbol: "😍" },
  { symbol: "🥰" },
  { symbol: "😋" },
  { symbol: "😎" },
  { symbol: "😌" },
  { symbol: "😉" },
  { symbol: "🙃" },
  { symbol: "😜" },
  { symbol: "🤪" },
  { symbol: "😝" },
  { symbol: "🤑" },
  { symbol: "🤗" },
  { symbol: "🤭" },
  { symbol: "🤫" },
  { symbol: "🤔" },
  { symbol: "🤐" },
  { symbol: "🤨" },
  { symbol: "😐" },
  { symbol: "😶" },
  { symbol: "😷" },
  { symbol: "🤭" },
  { symbol: "🤫" },
  { symbol: "🤔" },
  { symbol: "🤐" },
  { symbol: "🤨" },
  { symbol: "😐" },
  { symbol: "😶" },
  { symbol: "😷" },
];

// There are 30 emoji entries in the array.

export default emojiData;
